apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-frontend
  labels:
    app: next-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-frontend
  template:
    metadata:
      labels:
        app: next-frontend
    spec:
      containers:
        - name: next-frontend
          image: <YOUR_DOCKER_USERNAME>/next-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"